Adding Linked List Implementation
Manvityagi/Data-Structures-and-Algorithms pull request #22
Opened 2020-10-10 09:55 UTC by Vishal-raj-1

# Description

I have implement a singly linked list in CPP. Fixed #13 .

## Type of change

Please check options that are relevant to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New Data Structure 
- [] New Algorithm

# Checklist:

- [x] I have squashed my commits
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My code is a working bug-free code

2020-10-10 10:43 UTC, Manvityagi requested changes
@Vishal-raj-1  Please do the necessary update in DOCUMENTATION.md also, See how other things are listed there.

2020-10-10 10:54 UTC, ay2306 requested changes
Please include all CRUD operation of Linked List

2020-10-10 10:54 UTC, ay2306 commented on DS implementations/Linked List/list.cpp
> +} Node;
Do not `typedef` for changing the name `Node` to `Node`.

2020-10-10 13:15 UTC, Vishal-raj-1 commented
All conflicts and issues are resolved. @ay2306 @Manvityagi

2020-10-10 13:23 UTC, ay2306 commented
> All conflicts and issues are resolved. @ay2306 @Manvityagi

You have implemented the Create and Read node function only. Implement Update and Delete as well.

2020-10-10 13:42 UTC, Vishal-raj-1 commented
I have adding Delete and Reverse function.

2020-10-10 14:38 UTC, ay2306 requested changes
1. You haven't handled condition for `n` being greater than the size of the linked list for insert and delete operation
2. Implement Update for nth element as well.
3. You haven't squashed your commits, while you crossed the option in the PR description.

2020-10-10 17:25 UTC, Vishal-raj-1 commented
Sir i don't know how to squash commits, would you please help me a bit? I didn't get anything on google.

Thanks in advance.

2020-10-11 14:50 UTC, Vishal-raj-1 commented
Sir I have implement all functions. @ay2306

2020-10-12 12:13 UTC, Manvityagi requested changes
Squash your commits @Vishal-raj-1

2020-10-12 13:48 UTC, Vishal-raj-1 commented
Squashing of commits is done succesfully. @Manvityagi @ay2306

2020-10-12 14:00 UTC, Manvityagi commented
> Squashing of commits is done succesfully. @Manvityagi @ay2306
> 
> ![ss](https://user-images.githubusercontent.com/59874304/95754416-9ea80e00-0cc0-11eb-8978-15bd878d7cb3.JPG)

The PR still shows 10 commits @Vishal-raj-1

2020-10-12 14:25 UTC, Vishal-raj-1 commented
I don't know what to do😢. In git bash all previous commits were sqaushed into first commit. Which is mark in screenshot.

![sss](https://user-images.githubusercontent.com/59874304/95757009-30654a80-0cc4-11eb-999b-ad0b9b6b853f.JPG)

But it still show 10 commits on github.

![ss2](https://user-images.githubusercontent.com/59874304/95757300-9a7def80-0cc4-11eb-8cd3-15c7679fff4f.JPG)

**How to resolve this issue ?**

2020-10-12 14:26 UTC, Vishal-raj-1 commented
Could you please do squashing while merge this pull request ? @Manvityagi

2020-10-12 15:26 UTC, merged

2020-10-12 15:55 UTC, Vishal-raj-1 commented
Thanks for merging my pull request. @ay2306  @Manvityagi 😊