Create Linear search.cpp
Manvityagi/Data-Structures-and-Algorithms pull request #29
Opened 2020-10-12 14:29 UTC by kvanshika10

# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixed # (issue) (e.g. Fixed #8)

## Type of change

Please check options that are relevant to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New Data Structure 
- [ ] New Algorithm

# Checklist:

- [ ] I have squashed my commits
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My code is a working bug-free code

2020-10-12 14:42 UTC, Manvityagi requested changes
No changes in documentation done @kvanshika10

2020-10-12 14:44 UTC, Manvityagi requested changes
Also, you should create an issue also for the same

2020-10-12 14:58 UTC, ay2306 requested changes
Properly indent your code.

2020-10-13 12:41 UTC, Manvityagi approved these changes

2020-10-13 12:41 UTC, merged