Added-DS/Radix Sort Algorithm
Manvityagi/Data-Structures-and-Algorithms pull request #32
Opened 2020-10-13 16:37 UTC by Meghag5

# Description

Radix sort algorithm is implemented.

#7 

## Type of change

Please check options that are relevant to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New Data Structure 
- [x] New Algorithm

# Checklist:

- [x] I have squashed my commits
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My code is a working bug-free code

2020-10-14 09:15 UTC, ay2306 commented
You have again submitted the hidden files, please delete them and add `.DS_Store` to `.gitignore`

2020-10-14 09:26 UTC, ay2306 requested changes
The code seems logically flawed. However, I have just commented on the first read basis. Please check your code or if you think your code is correct tell me and I will test it as I have my suspicion on this code to be logically wrong.

2020-10-14 09:26 UTC, ay2306 commented on Algorithms/Sorting/RadixSort.cpp
> +    }
You need to check this part.

2020-10-14 09:26 UTC, ay2306 commented on Algorithms/Sorting/RadixSort.cpp
> +}
Radix sort is not just simply running counting sort `log(A)` times. On top of that, int div at line 44 is unnecessary.

2020-10-14 14:00 UTC, Meghag5 commented
@ay2306 pls check my code again. It's output is correct

2020-10-16 13:45 UTC, Meghag5 commented
@ay2306 all the changes are made pls check

2020-10-20 07:23 UTC, ay2306 commented
@Meghag5 Hey, sorry I had some doubts understanding the implementation this way. But after spending time on it, code makes sense. Merging your code.

2020-10-20 07:24 UTC, merged